[package]
name = "decision_transformer_dfdx"
version = "0.1.0"
edition = "2021"

[dependencies]
dfdx = { version = "0.13.0", features = ["safetensors"] }
num-traits = "0.2.19"
rand = "0.8.5"
rand_distr = "0.4.3"
